server:
  port: ${CONFIG_SERVER_PORT}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:shared/
        bootstrap: true
  profiles:
    active: native

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
