server:
  port: ${EUREKA_SERVER_PORT}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
    registerWithEureka: false
    fetchRegistry: false

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
